### ISSUE TITLE
[Bug]: Viewing events tab causes panel to crash when using `figwheel.main`'s `:target :bundle` option.

### ISSUE THREAD

**Issue by eval-on-point** [day8/re-frame-10x#346]
### What happened?

A bug happened! See some discussion in the Clojurians Slack [here](https://clojurians-log.clojureverse.org/re-frame/2022-01-07/1641588962.004100). I've prepared a minimal example [here](https://github.com/eval-on-point/re-frame-10x-bundle-bug).

### 10x Version

1.2.1

### Reagent Version

1.1.0

### React Version

17.0.2

### re-frame Version

1.2.0

### What browsers are you seeing the problem on?

Chrome

### Relevant console output

```shell
core.cljs:13 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at cmp.re_highlight$core$did_mount (core.cljs:13:6)
    at cmp.reagent$impl$component$custom_wrapper_$_componentDidMount [as componentDidMount] (component.cljs:240:25)
    at commitLifeCycles (react-dom.development.js:19814:22)
    at commitLayoutEffects (react-dom.development.js:22803:7)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:16)
    at invokeGuardedCallback (react-dom.development.js:292:31)
    at commitRootImpl (react-dom.development.js:22541:9)
    at unstable_runWithPriority (scheduler.development.js:653:12)
    at runWithPriority$1 (react-dom.development.js:11039:10)
```

**Comment by kimo-k** [comment]
We no longer depend on highlight.js, so hopefully this is fixed.
